'use strict'

require('./area/square-kilometer')
require('./area/hectare')
require('./area/decare')
require('./area/are')
require('./area/square-meter')
require('./area/square-decimeter')
require('./area/square-centimeter')
require('./area/square-millimeter')
require('./area/barn')
require('./area/township')
require('./area/square-mile')
require('./area/homestead')
require('./area/acre')
require('./area/rood')
require('./area/square-rod')
require('./area/perch')
require('./area/square')
require('./area/square-yard')
require('./area/square-foot')
require('./area/square-inch')
